# CI de Nivel N2 - Disparo manual a partir de 1 clique

# Nome do nosso pipiline
name: 'Execucao Agendada'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch

on:
  schedule:
    # cronograma de execuÃ§Ã£o do pipeline
    - cron: '0 3 4 6 *' # Executa diariamente Ã  meia-noite
    
    
# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    #mÃ¡quina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instala o node
      - uses: actions/setup-node@v4 
        with:
          node-version: 22.x 
          
      # instala o yarn
      - name: Instalando o Yarn
        run: npm install -g yarn

      # instala as dependÃªncias do projeto
      - name: Instala as dependÃªncias do projeto
        run: yarn 

      # Instalando Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # Executa os testes
      - name: Executa os testes E2E
        run: yarn run e2e

      - name: Notifica no Discord
        if: always() # executa mesmo se os testes falharem
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ğŸš€ *ExecuÃ§Ã£o agendada concluÃ­da!*
            ğŸ“… HorÃ¡rio: ${{ github.event.schedule }}
            ğŸ” RepositÃ³rio: `${{ github.repository }}`
            ğŸ§ª Resultado: `${{ job.status }}`