# CI de Nivel N2 - Disparo agendado e opcionalmente manual

name: 'Execucao Agendada'

on:
  # permite execuÃ§Ã£o manual, se necessÃ¡rio
  workflow_dispatch:

  schedule:
    - cron: '0 18 4 6 *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando o Yarn
        run: npm install -g yarn

      - name: Instala as dependÃªncias do projeto
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Executa os testes E2E
        run: yarn run e2e

      - name: Notifica no Discord
        if: always()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ğŸš€ *ExecuÃ§Ã£o agendada concluÃ­da!*
            ğŸ“… HorÃ¡rio (UTC): ${{ github.event.schedule || 'Manual' }}
            ğŸ” RepositÃ³rio: `${{ github.repository }}`
            ğŸ§ª Resultado: `${{ job.status }}`
