# CI de Nivel N2 - Disparo agendado e opcionalmente manual

name: 'Execucao Agendada'

on:
  # permite execução manual, se necessário
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando o Yarn
        run: npm install -g yarn

      - name: Instala as dependências do projeto
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Executa os testes E2E
        run: yarn run e2e

      